### PR TITLE
enable codeql

### PR DESCRIPTION
**Pull request by jmarolf**

### CODE REVIEW

**Comment by jmarolf** [comment]
@mavasani it doesn't look like I have permissions to run/test this change

**Review by arkalyanms — APPROVED** [review]

**Review by mavasani — APPROVED** [review]

**Comment by mavasani** [comment]
@jmarolf I have added you to the admin group for the repo.

Pipeline: https://dev.azure.com/dnceng/internal/_build?definitionId=956

I am not sure how to edit the pipeline to kick of the build for PRs for this repo. Triggers for the pipeline don't seem to be editable:
https://dev.azure.com/dnceng/internal/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=956&view=Tab_Triggers

**Pull request merged**
