### PR TITLE
Update extension to depend on .NET 6

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes https://github.com/dotnet/vscode-dotnet-pack/issues/22

### CODE REVIEW

**Comment by sfoslund** [comment]
@vatsalyaagrawal are we still bundling a version of the SDK along with the installer? I didn't see a way to update that version. Also, does CI generate an installer I can validate or is there another way I should plan on testing this?

@JoeRobich @jonsequitur @baronfel will updating the .NET 6 be okay for your extensions?

**Comment by baronfel** [comment]
Ionide should support this as of a couple of minor versions back (though support is not perfect), but we should be broadly functional. FSI scripts are not working on .net 6 currently, however (this is something we're actively working on).  @Krzysztof-Cieslak are you aware of any gigantic blockers?

**Comment by JoeRobich** [comment]
OmniSharp C# extension should work fine with .NET 6.0.

**Comment by sfoslund** [comment]
Ping @jonsequitur @vatsalyaagrawal

**Comment by mavasani** [comment]
> are we still bundling a version of the SDK along with the installer? I didn't see a way to update that version

@sfoslund Yes, you need to update the versions in the vscode-dotnet-installer repo: https://github.com/dotnet/vscode-dotnet-installer/search?q=5.0.203

> Also, does CI generate an installer I can validate or is there another way I should plan on testing this?

Yes, the CI for vscode-dotnet-installer repo should generate signed installer bits (both offline and online versions). However, you will need to publish this new version of the extension pack on the VSCode extension gallery for the installer to pick it up, it always picks up the latest. I don't know of an easy way to test the new extension pack along with the installer without actually publishing the extension pack on the gallery.

**Comment by mavasani** [comment]
Signed build pipeline for vscode-dotnet-installer repo is [here](https://dev.azure.com/dnceng/internal/_build?definitionId=944)

**Review by mavasani — APPROVED** [review]

**Comment by sfoslund** [comment]
> However, you will need to publish this new version of the extension pack on the VSCode extension gallery for the installer to pick it up, it always picks up the latest.

@mavasani okay, I don't think we want to publish an update to 6.0 until it's closer to GA, so should I leave this PR for now? How do the 2 repos interact? Which one publishes to the marketplace automatically? I'll prep the PR to update the version in vscode-dotnet-installer too

**Comment by mavasani** [comment]
None of the repos publish anything automatically. I think it should be safe to merge changes to both repos and publish both the extension and the installer when ready.

**Comment by sfoslund** [comment]
Ah, sorry, misread your last message :) Although looking at it now, I don't think we'll be able to merge the installer update until 6.0 GA's, since I don't think we want to install a preview by default. I'm going to set the installing version to 6.0.100 and we'll have to wait until that version actually exists

**Comment by sfoslund** [comment]
Installer PR: https://github.com/dotnet/vscode-dotnet-installer/pull/64

**Comment by mavasani** [comment]
I’ll publish the updated extension later today.

**Comment by sfoslund** [comment]
> I’ll publish the updated extension later today.

Do we need dotnet/vscode-dotnet-installer#64 in as well? Have we sanity tested to make sure all the new extensions are working with .NET 6?

**Comment by baronfel** [comment]
Can confirm that Ionide is working with .NET 6 👍

**Comment by JoeRobich** [comment]
C# extension is working with .NET 6.

**Pull request merged**
